export const DISTRICTS = [
  'East Khasi Hills',
  'West Khasi Hills',
  'South West Khasi Hills',
  'Ri Bhoi',
  'East Jaintia Hills',
  'West Jaintia Hills',
  'East Garo Hills',
  'West Garo Hills',
  'South Garo Hills',
  'North Garo Hills',
];

export const INTERESTS = ['nature', 'adventure', 'waterfalls', 'caves', 'culture', 'wildlife', 'heritage', 'lakes'];

export const ACTIVITIES = [
  'Trekking',
  'Photography',
  'Swimming',
  'Boating',
  'Bird watching',
  'Camping',
  'Cave exploration',
  'Kayaking',
  'Wildlife safari',
  'Cycling',
  'Zip-lining',
  'Sunrise viewing',
  'Village walk',
  'Cultural tour',
  'Fishing',
  'Guided tour',
  'Spelunking',
  'Rock climbing',
  'Rappelling',
  'Nature walk',
];

export const SEED_PLACES = [
  // ── East Khasi Hills – Shillong City ─────────────────────────────────────
  {
    name: "Ward's Lake",
    district: 'East Khasi Hills',
    description: "A charming artificial lake at the heart of Shillong, Ward's Lake is surrounded by manicured gardens and a Victorian-era bandstand. Paddle boating, flower gardens, and the famous Orchid Lake Resort make it a favourite.",
    image: '/images/wardslake.jpg',
    coordinates: { lat: 25.5729, lng: 91.8831 },
    tags: ['nature', 'culture', 'lakes'],
    budget: 'low',
    temperature: { min: 10, max: 22 },
    bestTime: 'October – May',
    highlights: ['Paddle boating', 'Japanese garden', 'Victorian bandstand', 'Orchid garden'],
    activities: ['Paddle boating', 'Garden walk', 'Photography', 'Picnic', 'Bird watching'],
    entryFee: '₹10',
    visitDuration: 2,
  },
  {
    name: 'Don Bosco Museum',
    district: 'East Khasi Hills',
    description: 'The largest museum in Northeast India, Don Bosco Centre for Indigenous Cultures houses over 17,000 artifacts showcasing the culture, traditions, and art of 200+ tribes across Northeast India. The sky-walk provides 360° views of Shillong.',
    image: '/images/donbosco.jpg',
    coordinates: { lat: 25.5773, lng: 91.8856 },
    tags: ['culture', 'heritage'],
    budget: 'low',
    temperature: { min: 10, max: 22 },
    bestTime: 'October – April',
    highlights: ['Largest NE India museum', '17,000+ artifacts', 'Sky-walk', 'Tribal art gallery'],
    activities: ['Museum tour', 'Cultural exploration', 'Sky-walk', 'Photography', 'Guided tour'],
    entryFee: '₹100',
    visitDuration: 3,
  },
  {
    name: 'Lady Hydari Park',
    district: 'East Khasi Hills',
    description: "Named after the wife of the first Governor of Assam, Lady Hydari Park in Shillong features a Japanese-style garden, a mini zoo, butterflies, and orchids. It's a peaceful urban retreat loved by locals and tourists alike.",
    image: '/images/ladyhydari.jpg',
    coordinates: { lat: 25.5706, lng: 91.8878 },
    tags: ['nature', 'culture'],
    budget: 'low',
    temperature: { min: 10, max: 22 },
    bestTime: 'October – May',
    highlights: ['Japanese garden', 'Mini zoo', 'Orchids', 'Butterfly park'],
    activities: ['Garden walk', 'Zoo visit', 'Photography', 'Picnic', 'Butterfly spotting'],
    entryFee: '₹10',
    visitDuration: 2,
  },
  {
    name: 'All Saints Cathedral',
    district: 'East Khasi Hills',
    description: "A magnificent Anglican cathedral built by Welsh missionaries in 1847, All Saints Cathedral is one of the oldest churches in Northeast India. Its Gothic architecture, stained-glass windows, and serene interior make it a landmark of colonial Shillong.",
    image: '/images/allsaints.jpg',
    coordinates: { lat: 25.5677, lng: 91.8831 },
    tags: ['culture', 'heritage'],
    budget: 'low',
    temperature: { min: 10, max: 22 },
    bestTime: 'October – May',
    highlights: ['Gothic architecture', 'Colonial heritage', 'Stained glass windows', '1847 church'],
    activities: ['Heritage walk', 'Photography', 'Sightseeing', 'Architectural tour'],
    entryFee: 'Free',
    visitDuration: 1,
  },
  {
    name: 'Cathedral of Mary Help of Christians',
    district: 'East Khasi Hills',
    description: "The largest Catholic cathedral in Meghalaya, the Cathedral of Mary Help of Christians stands atop a hill in Shillong with sweeping views of the city. Its twin towers and elegant façade are a highlight of any city walk.",
    image: '/images/cathedral.jpg',
    coordinates: { lat: 25.5742, lng: 91.8853 },
    tags: ['culture', 'heritage'],
    budget: 'low',
    temperature: { min: 10, max: 22 },
    bestTime: 'October – May',
    highlights: ['Twin towers', 'Hill-top location', 'City views', 'Catholic heritage'],
    activities: ['Heritage walk', 'Photography', 'Sightseeing', 'City views'],
    entryFee: 'Free',
    visitDuration: 1,
  },
  {
    name: 'Shillong View Point',
    district: 'East Khasi Hills',
    description: "Perched above Shillong city, this popular viewpoint offers sweeping panoramas of the Scottish-style hill station with its red-roofed houses, pine ridges, and surrounding mountains. Perfect for sunrise and sunset photography.",
    image: '/images/shillongview.jpg',
    coordinates: { lat: 25.5667, lng: 91.8833 },
    tags: ['nature', 'culture'],
    budget: 'low',
    temperature: { min: 10, max: 20 },
    bestTime: 'October – May',
    highlights: ['City panorama', 'Sunrise views', 'Pine-ridge backdrop', 'Photography'],
    activities: ['Sunrise viewing', 'Sunset watching', 'Photography', 'Sightseeing'],
    entryFee: 'Free',
    visitDuration: 1,
  },
  {
    name: 'Shillong Golf Course',
    district: 'East Khasi Hills',
    description: "Established in 1898, the Shillong Golf Club is one of the oldest golf courses in Asia and is set amidst stunning pine-forested hills. The 18-hole course at 1,500 m elevation offers a unique golfing experience with breathtaking Shillong views.",
    image: '/images/shillongview.jpg',
    coordinates: { lat: 25.5653, lng: 91.8986 },
    tags: ['nature', 'culture', 'heritage'],
    budget: 'high',
    temperature: { min: 10, max: 22 },
    bestTime: 'October – May',
    highlights: ['One of Asia\'s oldest golf courses', '18-hole championship course', 'Pine forest backdrop', '1,500 m elevation'],
    activities: ['Golf', 'Leisurely walk', 'Photography', 'Club dining', 'Sightseeing'],
    entryFee: '₹2,000 (greens fee)',
    visitDuration: 4,
  },
  {
    name: 'Smit Village',
    district: 'East Khasi Hills',
    description: "Smit is the cultural capital of the Khasi people and hosts the annual Nongkrem Dance Festival — one of the oldest festivals in Meghalaya. Traditional Khasi architecture, sacred groves, and local markets define this village.",
    image: '/images/smit.jpg',
    coordinates: { lat: 25.5, lng: 91.75 },
    tags: ['culture'],
    budget: 'low',
    temperature: { min: 10, max: 22 },
    bestTime: 'October – November',
    highlights: ['Nongkrem Dance Festival', 'Khasi culture', 'Sacred groves', 'Traditional markets'],
    activities: ['Cultural tour', 'Village walk', 'Festival attendance', 'Photography', 'Local food tasting'],
    entryFee: 'Free',
    visitDuration: 2,
  },
  {
    name: 'Eco Park Shillong',
    district: 'East Khasi Hills',
    description: "A family-friendly recreational park near Ward's Lake, Eco Park features landscaped gardens, cycling tracks, boating lake, and a children's play area. It's a popular picnic destination for families and couples enjoying Shillong's pleasant climate.",
    image: '/images/ladyhydari.jpg',
    coordinates: { lat: 25.5714, lng: 91.8848 },
    tags: ['nature'],
    budget: 'low',
    temperature: { min: 10, max: 22 },
    bestTime: 'October – May',
    highlights: ['Cycling tracks', 'Boating lake', 'Children\'s play area', 'Landscaped gardens'],
    activities: ['Cycling', 'Paddle boating', 'Picnic', 'Nature walk', 'Photography', 'Family recreation'],
    entryFee: '₹20',
    visitDuration: 2,
  },
  {
    name: 'Lum Sohpetbneng Peak',
    district: 'East Khasi Hills',
    description: "Considered the navel of heaven by the Khasi people, Lum Sohpetbneng is a sacred flat-topped hill 25 km from Shillong. This deeply spiritual site offers panoramic views of the Brahmaputra plains and is central to Khasi creation mythology.",
    image: '/images/shillongpeak.jpg',
    coordinates: { lat: 25.7253, lng: 91.8625 },
    tags: ['culture', 'nature', 'heritage'],
    budget: 'low',
    temperature: { min: 10, max: 22 },
    bestTime: 'October – May',
    highlights: ['Sacred Khasi site', 'Flat-topped sacred hill', 'Brahmaputra plains view', 'Creation mythology'],
    activities: ['Sacred site visit', 'Trekking', 'Photography', 'Cultural tour', 'Sunrise viewing'],
    entryFee: 'Free',
    visitDuration: 2,
  },

  // ── East Khasi Hills – Shillong Outskirts ────────────────────────────────
  {
    name: 'Shillong Peak',
    district: 'East Khasi Hills',
    description: "The highest peak near Shillong at 1,965 m, offering panoramic views of the city and surrounding hills. Managed by the Indian Air Force, this is the perfect spot to watch the sunrise over the valley.",
    image: '/images/shillongpeak.jpg',
    coordinates: { lat: 25.5308, lng: 91.9189 },
    tags: ['nature', 'adventure'],
    budget: 'low',
    temperature: { min: 8, max: 20 },
    bestTime: 'September – May',
    highlights: ['Panoramic views', 'Sunrise point', 'Air Force base', 'Pine forests'],
    activities: ['Sunrise viewing', 'Photography', 'Trekking', 'Paragliding (seasonal)', 'Sightseeing'],
    entryFee: '₹20',
    visitDuration: 2,
  },
  {
    name: 'Elephant Falls',
    district: 'East Khasi Hills',
    description: "One of the most popular waterfalls near Shillong, Elephant Falls descends in three tiers through lush green surroundings. Named by the British after a rock shaped like an elephant that was lost in an earthquake.",
    image: '/images/elephantfalls.jpg',
    coordinates: { lat: 25.5436, lng: 91.8458 },
    tags: ['waterfalls', 'nature'],
    budget: 'low',
    temperature: { min: 12, max: 22 },
    bestTime: 'July – September',
    highlights: ['Three-tiered falls', 'Easy access', 'Scenic trails', 'Photography'],
    activities: ['Photography', 'Nature walk', 'Waterfall viewing', 'Picnic'],
    entryFee: '₹20',
    visitDuration: 2,
  },
  {
    name: 'Umiam Lake',
    district: 'Ri Bhoi',
    description: "A large reservoir 15 km north of Shillong, Umiam Lake's serene blue waters backed by pine-covered hills offer a peaceful retreat. Water sports, boating, and lakeside picnics are popular activities.",
    image: '/images/umiam.jpg',
    coordinates: { lat: 25.6333, lng: 91.9167 },
    tags: ['nature', 'adventure', 'lakes'],
    budget: 'medium',
    temperature: { min: 10, max: 22 },
    bestTime: 'October – May',
    highlights: ['Water sports', 'Boating', 'Pine-hill backdrop', 'Picnic spots'],
    activities: ['Boating', 'Kayaking', 'Water skiing', 'Cycling', 'Picnic', 'Photography', 'Swimming'],
    entryFee: '₹50',
    visitDuration: 3,
  },
  {
    name: 'Laitlum Canyons',
    district: 'East Khasi Hills',
    description: "Dubbed the 'Grand Canyon of the East,' Laitlum offers breathtaking views of deep gorges, valleys, and rolling hills. The winding path down the canyon and the solitude make it a trekker's paradise.",
    image: '/images/laitlum.jpg',
    coordinates: { lat: 25.4756, lng: 91.9428 },
    tags: ['nature', 'adventure'],
    budget: 'low',
    temperature: { min: 10, max: 20 },
    bestTime: 'October – May',
    highlights: ['Grand Canyon views', 'Trekking trails', 'Valley panoramas', 'Sunrise/sunset'],
    activities: ['Trekking', 'Photography', 'Sunrise viewing', 'Sunset watching', 'Camping'],
    entryFee: 'Free',
    visitDuration: 3,
  },
  {
    name: 'Mawphlang Sacred Forest',
    district: 'East Khasi Hills',
    description: "One of Meghalaya's last surviving sacred groves, Mawphlang has been protected by the Khasi people for over 1,000 years. Nothing can be removed from the forest — a living example of indigenous conservation.",
    image: '/images/mawphlang.jpg',
    coordinates: { lat: 25.4167, lng: 91.8333 },
    tags: ['nature', 'culture'],
    budget: 'low',
    temperature: { min: 8, max: 18 },
    bestTime: 'October – May',
    highlights: ['Sacred grove', '1,000 years old', 'Guided walks', 'Ancient monoliths'],
    activities: ['Guided nature walk', 'Bird watching', 'Photography', 'Cultural tour', 'Meditation'],
    entryFee: '₹30',
    visitDuration: 2,
  },
  {
    name: 'Mawkdok Dympep Valley',
    district: 'East Khasi Hills',
    description: "Situated on the Shillong–Cherrapunji road, Mawkdok offers spectacular valley views and is the starting point for zip-line adventures. The viewpoint is perfect for photography and experiencing Meghalaya's dramatic landscape.",
    image: '/images/mawkdok.jpg',
    coordinates: { lat: 25.3667, lng: 91.7417 },
    tags: ['nature', 'adventure'],
    budget: 'medium',
    temperature: { min: 12, max: 22 },
    bestTime: 'October – May',
    highlights: ['Zip-line', 'Valley viewpoint', 'Photography', 'Scenic drive'],
    activities: ['Zip-lining', 'Photography', 'Valley viewing', 'Rock climbing (guided)', 'Rappelling'],
    entryFee: '₹500 (zip-line)',
    visitDuration: 2,
  },
  {
    name: 'Jakrem Hot Springs',
    district: 'East Khasi Hills',
    description: "The only sulphur hot springs in Meghalaya, Jakrem is believed to have medicinal properties. Visitors come to soak in the warm sulphur pools against a backdrop of pine-forested hills.",
    image: '/images/jakrem.jpg',
    coordinates: { lat: 25.3167, lng: 91.7167 },
    tags: ['nature'],
    budget: 'low',
    temperature: { min: 10, max: 22 },
    bestTime: 'October – May',
    highlights: ['Sulphur hot springs', 'Medicinal properties', 'Pine forest views', 'Relaxation'],
    activities: ['Hot spring bathing', 'Relaxation', 'Photography', 'Nature walk'],
    entryFee: '₹30',
    visitDuration: 2,
  },
  {
    name: 'Weisawdong Falls',
    district: 'East Khasi Hills',
    description: 'Hidden near Mawphlong, Weisawdong is a pristine twin waterfall accessible through a scenic trek. Surrounded by dense forest and rocky terrain, it remains unspoilt and serene — a hidden gem for nature lovers.',
    image: '/images/weisawdong.jpg',
    coordinates: { lat: 25.41, lng: 91.82 },
    tags: ['waterfalls', 'nature', 'adventure'],
    budget: 'low',
    temperature: { min: 10, max: 22 },
    bestTime: 'July – September',
    highlights: ['Twin waterfalls', 'Forest trek', 'Pristine nature', 'Hidden gem'],
    activities: ['Trekking', 'Swimming', 'Photography', 'Nature walk', 'Waterfall viewing'],
    entryFee: 'Free',
    visitDuration: 3,
  },
  {
    name: 'Mawlyngbna',
    district: 'East Khasi Hills',
    description: 'A nature adventure village 40 km from Shillong, Mawlyngbna offers trekking, swimming in natural pools, kayaking, and village walks through terraced fields. It is a model eco-tourism village promoted by local NGOs.',
    image: '/images/mawlyngbna.jpg',
    coordinates: { lat: 25.32, lng: 91.71 },
    tags: ['adventure', 'nature'],
    budget: 'medium',
    temperature: { min: 14, max: 26 },
    bestTime: 'October – May',
    highlights: ['Eco-tourism', 'Natural pools', 'Kayaking', 'Village homestays'],
    activities: ['Trekking', 'Kayaking', 'Swimming', 'Village walk', 'Rock climbing', 'Rappelling', 'Cycling'],
    entryFee: '₹100',
    visitDuration: 3,
  },
  {
    name: 'David Scott Trail',
    district: 'East Khasi Hills',
    description: "A historic 16 km mountain trail built by British administrator David Scott in the early 19th century, connecting Cherrapunji road with Mawphlang. The trail passes through pine forests, river crossings, and ancient Khasi villages.",
    image: '/images/davids.jpg',
    coordinates: { lat: 25.5156, lng: 91.8542 },
    tags: ['adventure', 'culture', 'nature', 'heritage'],
    budget: 'low',
    temperature: { min: 10, max: 20 },
    bestTime: 'October – May',
    highlights: ['Historic 16 km trail', 'British-era path', 'Khasi villages', 'River crossings'],
    activities: ['Trekking', 'Mountain biking', 'Photography', 'Heritage walk', 'Bird watching'],
    entryFee: 'Free',
    visitDuration: 6,
  },
  {
    name: 'Bophill Falls',
    district: 'East Khasi Hills',
    description: "A serene twin waterfall hidden in the outskirts of Shillong, Bophill Falls descends through rocky cliffs into a crystal pool. The short trek through bamboo groves to reach it is refreshing and relatively easy.",
    image: '/images/bophill.jpg',
    coordinates: { lat: 25.4833, lng: 91.8333 },
    tags: ['waterfalls', 'nature'],
    budget: 'low',
    temperature: { min: 12, max: 24 },
    bestTime: 'July – September',
    highlights: ['Twin waterfall', 'Rocky cliffs', 'Natural pool', 'Easy trek'],
    activities: ['Photography', 'Swimming', 'Trekking', 'Picnic'],
    entryFee: 'Free',
    visitDuration: 2,
  },
  {
    name: 'Langkawet Falls',
    district: 'East Khasi Hills',
    description: "A picturesque multi-step waterfall near Shillong, Langkawet is relatively undiscovered and offers a quiet natural retreat. The falls cascade through dense subtropical vegetation into a small emerald pool below.",
    image: '/images/langkawet.jpg',
    coordinates: { lat: 25.46, lng: 91.80 },
    tags: ['waterfalls', 'nature'],
    budget: 'low',
    temperature: { min: 12, max: 24 },
    bestTime: 'July – October',
    highlights: ['Multi-step falls', 'Dense vegetation', 'Emerald pool', 'Offbeat destination'],
    activities: ['Photography', 'Swimming', 'Trekking', 'Nature walk'],
    entryFee: 'Free',
    visitDuration: 2,
  },
  {
    name: 'Lumsohpet',
    district: 'East Khasi Hills',
    description: "Lumsohpet is a tranquil natural spot near Shillong's outskirts with gentle streams, open meadows, and pine forests. It's a favourite weekend escape for Shillong residents looking for a quiet picnic away from the city.",
    image: '/images/lumsohpet.jpg',
    coordinates: { lat: 25.45, lng: 91.85 },
    tags: ['nature'],
    budget: 'low',
    temperature: { min: 10, max: 22 },
    bestTime: 'October – May',
    highlights: ['Pine meadows', 'Gentle streams', 'Picnic spot', 'Weekend escape'],
    activities: ['Picnic', 'Nature walk', 'Photography', 'Stream play', 'Relaxation'],
    entryFee: 'Free',
    visitDuration: 2,
  },
  {
    name: 'Riangdo Waterfalls',
    district: 'Ri Bhoi',
    description: "A hidden cascade in the Ri Bhoi district, Riangdo Falls tumbles through dense forest into a clear pool, making it a perfect off-the-beaten-path destination. The surroundings are alive with birdsong and butterflies.",
    image: '/images/langkawet.jpg',
    coordinates: { lat: 25.72, lng: 91.98 },
    tags: ['waterfalls', 'nature', 'adventure'],
    budget: 'low',
    temperature: { min: 14, max: 26 },
    bestTime: 'July – October',
    highlights: ['Hidden waterfall', 'Clear pool', 'Dense forest', 'Bird watching'],
    activities: ['Swimming', 'Trekking', 'Photography', 'Bird watching', 'Nature walk'],
    entryFee: 'Free',
    visitDuration: 2,
  },

  // ── Cherrapunji (Sohra) ───────────────────────────────────────────────────
  {
    name: 'Nohkalikai Falls',
    district: 'East Khasi Hills',
    description: "India's tallest plunge waterfall at 340 m, Nohkalikai cascades dramatically into a stunning turquoise pool near Cherrapunji. Named after a tragic local legend, it is most spectacular during and just after monsoon season.",
    image: '/images/nohkalikai.jpg',
    coordinates: { lat: 25.2583, lng: 91.7042 },
    tags: ['waterfalls', 'nature', 'adventure'],
    budget: 'low',
    temperature: { min: 12, max: 24 },
    bestTime: 'October – May',
    highlights: ['340 m plunge waterfall', 'Turquoise pool', 'Viewpoints', 'Local legend trail'],
    activities: ['Photography', 'Viewpoint visit', 'Trekking to base', 'Nature walk', 'Sunset watching'],
    entryFee: '₹20',
    visitDuration: 2,
  },
  {
    name: 'Double Decker Living Root Bridge',
    district: 'East Khasi Hills',
    description: "A breathtaking natural wonder in Nongriat village, this unique double-decker bridge is formed by training the aerial roots of rubber fig trees over centuries. The trek through dense jungle to reach it is an adventure in itself.",
    image: '/images/doubledecker.jpg',
    coordinates: { lat: 25.2833, lng: 91.7167 },
    tags: ['nature', 'adventure', 'culture'],
    budget: 'medium',
    temperature: { min: 15, max: 26 },
    bestTime: 'October – April',
    highlights: ['Centuries-old living bridge', '3,500 step trek', 'Natural swimming pools', 'Jungle walk'],
    activities: ['Trekking', 'Swimming', 'Photography', 'Nature walk', 'Village visit'],
    entryFee: '₹50',
    visitDuration: 5,
  },
  {
    name: 'Seven Sisters Falls',
    district: 'East Khasi Hills',
    description: 'Known locally as Nohsngithiang, this majestic seven-segmented waterfall near Mawsmai is one of the tallest falls in the subcontinent. It flows strongest during the monsoon, creating a dramatic visual spectacle.',
    image: '/images/sevensisters.jpg',
    coordinates: { lat: 25.2736, lng: 91.7014 },
    tags: ['waterfalls', 'nature'],
    budget: 'low',
    temperature: { min: 12, max: 24 },
    bestTime: 'July – September',
    highlights: ['Seven-segmented falls', 'Viewpoint platform', 'Monsoon spectacle', 'Valley views'],
    activities: ['Photography', 'Viewpoint visit', 'Sightseeing'],
    entryFee: 'Free',
    visitDuration: 1,
  },
  {
    name: 'Mawsmai Cave',
    district: 'East Khasi Hills',
    description: "One of the most accessible limestone caves in Meghalaya, Mawsmai Cave is illuminated and features stunning stalactites and stalagmites. A 150-metre walkway winds through the cave's natural chambers.",
    image: '/images/mawsmai.jpg',
    coordinates: { lat: 25.2553, lng: 91.7128 },
    tags: ['caves', 'adventure'],
    budget: 'low',
    temperature: { min: 10, max: 18 },
    bestTime: 'October – April',
    highlights: ['Illuminated cave', 'Stalactites & stalagmites', '150 m walkway', 'Natural chambers'],
    activities: ['Cave exploration', 'Guided tour', 'Photography', 'Spelunking'],
    entryFee: '₹30',
    visitDuration: 1,
  },
  {
    name: 'Arwah Cave',
    district: 'East Khasi Hills',
    description: "Located near Cherrapunji, Arwah Cave is famous for its fossils, the Khasi legend of the lost goddess, and a river flowing inside. It's less crowded than Mawsmai, offering a more authentic caving experience.",
    image: '/images/arwah.jpg',
    coordinates: { lat: 25.2667, lng: 91.7167 },
    tags: ['caves', 'adventure'],
    budget: 'low',
    temperature: { min: 10, max: 20 },
    bestTime: 'October – April',
    highlights: ['Ancient fossils', 'Underground river', 'Khasi legends', 'Stalactites'],
    activities: ['Cave exploration', 'Fossil spotting', 'Guided tour', 'Photography'],
    entryFee: '₹20',
    visitDuration: 1,
  },
  {
    name: 'Garden of Caves',
    district: 'East Khasi Hills',
    description: "A unique cluster of seven limestone caves near Cherrapunji, Garden of Caves has beautifully lit natural chambers, cascading water, and a garden setting. It's perfect for families and casual explorers.",
    image: '/images/gardenofcaves.jpg',
    coordinates: { lat: 25.27, lng: 91.72 },
    tags: ['caves', 'nature'],
    budget: 'low',
    temperature: { min: 12, max: 22 },
    bestTime: 'October – April',
    highlights: ['Seven caves', 'Garden setting', 'Lit chambers', 'Family-friendly'],
    activities: ['Cave exploration', 'Photography', 'Family outing', 'Nature walk'],
    entryFee: '₹30',
    visitDuration: 2,
  },
  {
    name: 'Dainthlen Falls',
    district: 'East Khasi Hills',
    description: "Dainthlen Falls near Cherrapunji is linked to a Khasi legend about a giant serpent slain by a hero. The waterfall tumbles into a gorge with a picturesque pool, and the myth adds mystique to the scenic beauty.",
    image: '/images/dainthlen.jpg',
    coordinates: { lat: 25.2667, lng: 91.72 },
    tags: ['waterfalls', 'nature'],
    budget: 'low',
    temperature: { min: 12, max: 24 },
    bestTime: 'July – September',
    highlights: ['Legendary waterfall', 'Gorge pool', 'Local mythology', 'Photography'],
    activities: ['Photography', 'Mythology trail', 'Waterfall viewing', 'Picnic'],
    entryFee: 'Free',
    visitDuration: 1,
  },
  {
    name: 'Wahkaba Falls',
    district: 'East Khasi Hills',
    description: "Wahkaba Falls, also known as Bishop Falls, is a hidden waterfall near Cherrapunji accessible via a short trek through lush green meadows. Less visited than other falls, it provides a peaceful, intimate natural experience.",
    image: '/images/wahkaba.jpg',
    coordinates: { lat: 25.27, lng: 91.73 },
    tags: ['waterfalls', 'nature'],
    budget: 'low',
    temperature: { min: 12, max: 24 },
    bestTime: 'July – September',
    highlights: ['Hidden waterfall', 'Meadow trek', 'Peaceful atmosphere', 'Photography'],
    activities: ['Trekking', 'Photography', 'Nature walk', 'Relaxation'],
    entryFee: 'Free',
    visitDuration: 2,
  },
  {
    name: 'Mawmluh Cave',
    district: 'East Khasi Hills',
    description: "One of the longest caves in the Indian subcontinent, Mawmluh Cave near Cherrapunji stretches for 7.1 km. Its passages contain a wealth of stalactites, stalagmites, and an underground stream that emerges as a scenic waterfall.",
    image: '/images/mawmluh.jpg',
    coordinates: { lat: 25.2667, lng: 91.73 },
    tags: ['caves', 'adventure'],
    budget: 'medium',
    temperature: { min: 10, max: 18 },
    bestTime: 'October – April',
    highlights: ['7.1 km cave', 'Underground stream', 'Stalactites', 'Expert guided only'],
    activities: ['Expert caving', 'Spelunking', 'Guided tour', 'Photography', 'Underground stream crossing'],
    entryFee: '₹200',
    visitDuration: 4,
  },
  {
    name: 'Kynrem Falls',
    district: 'East Khasi Hills',
    description: "Kynrem Falls in Thangkharang Park near Cherrapunji is a three-tiered waterfall plunging 305 m into the valley below. Set against the backdrop of the Bangladesh plains, the view from the top is absolutely spectacular.",
    image: '/images/kynrem.jpg',
    coordinates: { lat: 25.2333, lng: 91.7167 },
    tags: ['waterfalls', 'nature', 'adventure'],
    budget: 'low',
    temperature: { min: 12, max: 24 },
    bestTime: 'July – September',
    highlights: ['305 m waterfall', 'Three-tiered falls', 'Bangladesh plains view', 'Thangkharang Park'],
    activities: ['Photography', 'Viewpoint visit', 'Park walk', 'Sightseeing', 'Trekking'],
    entryFee: '₹20',
    visitDuration: 2,
  },
  {
    name: 'Krem Dam Cave',
    district: 'East Khasi Hills',
    description: "Krem Dam is a river cave system near Cherrapunji carved by an underground stream. Unlike illuminated tourist caves, Krem Dam offers an authentic, raw caving experience through narrow passages and large fossil chambers.",
    image: '/images/kremdam.jpg',
    coordinates: { lat: 25.28, lng: 91.74 },
    tags: ['caves', 'adventure'],
    budget: 'medium',
    temperature: { min: 10, max: 18 },
    bestTime: 'October – April',
    highlights: ['River cave system', 'Fossil chambers', 'Underground stream', 'Adventure caving'],
    activities: ['Cave exploration', 'Spelunking', 'Fossil spotting', 'Guided caving tour'],
    entryFee: '₹100',
    visitDuration: 3,
  },
  {
    name: 'Liat Prah Sacred Forest',
    district: 'East Khasi Hills',
    description: "One of Meghalaya's protected sacred groves near Cherrapunji, Liat Prah is a mystical forest with ancient trees, mossy boulders, and crystal streams. Governed by community laws, it remains one of the most pristine forest patches in the region.",
    image: '/images/liatprah.jpg',
    coordinates: { lat: 25.27, lng: 91.72 },
    tags: ['nature', 'culture'],
    budget: 'low',
    temperature: { min: 12, max: 22 },
    bestTime: 'October – May',
    highlights: ['Sacred grove', 'Ancient trees', 'Community-protected', 'Crystal streams'],
    activities: ['Guided nature walk', 'Bird watching', 'Photography', 'Cultural learning', 'Meditation'],
    entryFee: 'Free',
    visitDuration: 2,
  },
  {
    name: 'Mawphanlur',
    district: 'East Khasi Hills',
    description: "Known as the 'Lake District of Meghalaya', Mawphanlur is a high-altitude plateau dotted with small blue lakes, rolling grasslands, and sacred forests. The plateau is ideal for peaceful walks, birdwatching, and camping.",
    image: '/images/mawphanlur.jpg',
    coordinates: { lat: 25.34, lng: 91.68 },
    tags: ['nature', 'adventure', 'lakes'],
    budget: 'low',
    temperature: { min: 8, max: 18 },
    bestTime: 'October – May',
    highlights: ['Lake District of Meghalaya', 'High-altitude plateau', 'Birdwatching', 'Rolling grasslands'],
    activities: ['Trekking', 'Bird watching', 'Camping', 'Photography', 'Boating (small boats)', 'Nature walk'],
    entryFee: 'Free',
    visitDuration: 3,
  },
  {
    name: 'PhePhe Falls',
    district: 'East Khasi Hills',
    description: "One of the tallest and most remote waterfalls in Meghalaya, PhePhe Falls near Mawsynram drops 210 m in a single dramatic plunge. The trek to the viewpoint passes through dense cloud forests and rewards with a spectacular view of the falls framed against the Bangladesh plains.",
    image: '/images/phephe.jpg',
    coordinates: { lat: 25.295, lng: 91.582 },
    tags: ['waterfalls', 'nature', 'adventure'],
    budget: 'low',
    temperature: { min: 12, max: 24 },
    bestTime: 'July – September',
    highlights: ['210 m plunge fall', 'Cloud forest trek', 'Bangladesh plains view', 'Remote & pristine'],
    activities: ['Trekking', 'Photography', 'Bird watching', 'Viewpoint visit'],
    entryFee: 'Free',
    visitDuration: 3,
  },
  {
    name: 'Weinia Falls',
    district: 'East Khasi Hills',
    description: "Weinia Falls is a powerful waterfall near Cherrapunji that drops into a deep gorge shrouded in mist. Its relative obscurity keeps crowds away, making it a pristine nature escape for adventurous hikers.",
    image: '/images/weinia.jpg',
    coordinates: { lat: 25.26, lng: 91.71 },
    tags: ['waterfalls', 'nature', 'adventure'],
    budget: 'low',
    temperature: { min: 12, max: 24 },
    bestTime: 'July – September',
    highlights: ['Deep gorge waterfall', 'Misty atmosphere', 'Off-beaten-path', 'Hiker favourite'],
    activities: ['Trekking', 'Photography', 'Waterfall viewing', 'Nature walk'],
    entryFee: 'Free',
    visitDuration: 2,
  },
  {
    name: 'Mawsynram',
    district: 'East Khasi Hills',
    description: "The world's wettest place by average annual rainfall (11,872 mm), Mawsynram experiences rainfall almost year-round. Its main attraction is Mawjymbuin Cave featuring a stalagmite shaped like a Shiva lingam, surrounded by perpetual mist and lush cloud forest.",
    image: '/images/mawkdok.jpg',
    coordinates: { lat: 25.2981, lng: 91.5820 },
    tags: ['nature', 'caves', 'heritage'],
    budget: 'low',
    temperature: { min: 10, max: 22 },
    bestTime: 'October – May',
    highlights: ["World's wettest place", 'Mawjymbuin Cave', 'Shiva lingam stalagmite', 'Cloud forest'],
    activities: ['Cave exploration', 'Photography', 'Village walk', 'Monsoon experience', 'Sightseeing'],
    entryFee: '₹20',
    visitDuration: 3,
  },

  // ── Dawki & Mawlynnong ───────────────────────────────────────────────────
  {
    name: 'Mawlynnong',
    district: 'South West Khasi Hills',
    description: "Asia's cleanest village is a remarkable model of community hygiene and eco-tourism. Flower-lined bamboo paths, sky-walks, and the living root bridge at Riwai make this a must-visit cultural destination.",
    image: '/images/mawlynnong.jpg',
    coordinates: { lat: 25.2028, lng: 91.9158 },
    tags: ['culture', 'nature'],
    budget: 'low',
    temperature: { min: 16, max: 28 },
    bestTime: 'October – May',
    highlights: ["Asia's cleanest village", 'Sky-walk platform', 'Bamboo pathways', 'Community homestays'],
    activities: ['Village walk', 'Sky-walk', 'Photography', 'Eco-tourism', 'Local food tasting', 'Cycling'],
    entryFee: 'Free',
    visitDuration: 3,
  },
  {
    name: 'Dawki & Umngot River',
    district: 'East Khasi Hills',
    description: "The crystal-clear Umngot River at Dawki is so transparent that boats appear to float on air. Located near the Bangladesh border, it's famous for its surreal clarity and emerald green hues.",
    image: '/images/dawki.jpg',
    coordinates: { lat: 25.1833, lng: 92.0167 },
    tags: ['nature', 'adventure'],
    budget: 'medium',
    temperature: { min: 18, max: 30 },
    bestTime: 'November – April',
    highlights: ['Crystal-clear river', 'Boating', 'Suspension bridge', 'Border town charm'],
    activities: ['Boating', 'Snorkelling', 'Swimming', 'Photography', 'Fishing', 'Suspension bridge walk'],
    entryFee: '₹100 (boating)',
    visitDuration: 3,
  },
  {
    name: 'Shnongpdeng',
    district: 'East Khasi Hills',
    description: "A riverside camping and adventure hub near Dawki, Shnongpdeng is famous for its transparent Umngot River, cliff jumping, snorkelling, and camping under the stars beside the crystal-clear water.",
    image: '/images/shnongpdeng.jpg',
    coordinates: { lat: 25.1833, lng: 92.0333 },
    tags: ['adventure', 'nature'],
    budget: 'medium',
    temperature: { min: 18, max: 30 },
    bestTime: 'October – May',
    highlights: ['Cliff jumping', 'Snorkelling', 'Riverside camping', 'Crystal-clear river'],
    activities: ['Cliff jumping', 'Snorkelling', 'Camping', 'Kayaking', 'Photography', 'Swimming', 'Zip-lining'],
    entryFee: '₹100',
    visitDuration: 2,
  },
  {
    name: 'Riwai Living Root Bridge',
    district: 'South West Khasi Hills',
    description: "Located near Mawlynnong, the Riwai single-decker root bridge is the most accessible living root bridge in Meghalaya. This ancient bio-engineering marvel formed over generations is a short walk from the village.",
    image: '/images/riwai.jpg',
    coordinates: { lat: 25.197, lng: 91.872 },
    tags: ['nature', 'adventure', 'culture'],
    budget: 'low',
    temperature: { min: 16, max: 28 },
    bestTime: 'October – April',
    highlights: ['Living root bridge', 'Easy access', 'Jungle walk', 'Photography'],
    activities: ['Root bridge crossing', 'Photography', 'Nature walk', 'Cultural learning'],
    entryFee: 'Free',
    visitDuration: 2,
  },
  {
    name: 'Kongthong (Whistling Village)',
    district: 'East Khasi Hills',
    description: "Kongthong is famous for its extraordinary tradition of giving each person a unique whistled tune as their identity — a practice called Jingrwai Lawbei. Visiting this village feels like stepping into a living cultural museum.",
    image: '/images/kongthong.jpg',
    coordinates: { lat: 25.0833, lng: 91.8333 },
    tags: ['culture', 'nature'],
    budget: 'low',
    temperature: { min: 14, max: 26 },
    bestTime: 'October – May',
    highlights: ['Whistled name tradition', 'Cultural immersion', 'Village walk', 'Panoramic views'],
    activities: ['Cultural immersion', 'Village walk', 'Photography', 'Traditional music learning'],
    entryFee: 'Free',
    visitDuration: 2,
  },
  {
    name: 'Ranikor',
    district: 'South West Khasi Hills',
    description: "A remote riverside village in South West Khasi Hills on the banks of the Kynshi River, Ranikor is famed for its crystal-clear emerald waters, fishing, and pristine nature. The river is a kayaker's and angler's paradise rarely touched by mainstream tourism.",
    image: '/images/dawki.jpg',
    coordinates: { lat: 25.225, lng: 91.388 },
    tags: ['nature', 'adventure'],
    budget: 'low',
    temperature: { min: 18, max: 30 },
    bestTime: 'November – April',
    highlights: ['Crystal Kynshi River', 'Angling', 'Riverside camping', 'Remote wilderness'],
    activities: ['Kayaking', 'Fishing & angling', 'River camping', 'Swimming', 'Photography', 'Boating'],
    entryFee: 'Free',
    visitDuration: 2,
  },
  {
    name: 'Laitmawsiang Root Bridge',
    district: 'South West Khasi Hills',
    description: "A lesser-known single-decker living root bridge in Laitmawsiang village, this centuries-old bio-engineering marvel is surrounded by thick jungle and is far less crowded than Nongriat. The trek through the Khasi countryside adds to its charm.",
    image: '/images/riwai.jpg',
    coordinates: { lat: 25.19, lng: 91.85 },
    tags: ['nature', 'adventure', 'culture'],
    budget: 'low',
    temperature: { min: 16, max: 28 },
    bestTime: 'October – April',
    highlights: ['Living root bridge', 'Less crowded', 'Jungle trek', 'Khasi village'],
    activities: ['Trekking', 'Root bridge crossing', 'Photography', 'Village walk', 'Nature exploration'],
    entryFee: 'Free',
    visitDuration: 3,
  },

  // ── Jaintia Hills ─────────────────────────────────────────────────────────
  {
    name: 'Krangsuri Waterfall',
    district: 'West Jaintia Hills',
    description: "Hidden in the dense forests of Jaintia Hills, Krangsuri is a multi-tiered waterfall that flows over a wide rocky ledge into a turquoise pool ideal for swimming. The bamboo raft crossing adds to its charm.",
    image: '/images/krangsuri.jpg',
    coordinates: { lat: 25.4167, lng: 92.5833 },
    tags: ['waterfalls', 'nature', 'adventure'],
    budget: 'low',
    temperature: { min: 18, max: 30 },
    bestTime: 'October – April',
    highlights: ['Multi-tiered falls', 'Natural swimming pool', 'Bamboo raft crossing', 'Jungle trails'],
    activities: ['Swimming', 'Photography', 'Bamboo raft ride', 'Trekking', 'Waterfall viewing'],
    entryFee: '₹50',
    visitDuration: 3,
  },
  {
    name: 'Nongkhnum Island',
    district: 'West Jaintia Hills',
    description: "The largest river island in Meghalaya, Nongkhnum sits in the Myntdu river and is accessible by a small wooden bridge. Its beaches, clear waters, and lush grasslands make it a unique eco-tourism destination.",
    image: '/images/nongkhnum.jpg',
    coordinates: { lat: 25.4167, lng: 91.5833 },
    tags: ['nature', 'adventure'],
    budget: 'low',
    temperature: { min: 16, max: 28 },
    bestTime: 'October – May',
    highlights: ['River island', 'River beaches', 'Sandy shores', 'Eco-tourism'],
    activities: ['River swimming', 'Picnic', 'Photography', 'Bird watching', 'Camping', 'Cycling'],
    entryFee: 'Free',
    visitDuration: 4,
  },
  {
    name: 'Thadlaskein Lake',
    district: 'West Jaintia Hills',
    description: "An idyllic man-made lake surrounded by green hills in Jowai, Thadlaskein is a serene picnic spot. The lake is sacred to the Pnar people and is dotted with monoliths. Boating and fishing are popular activities.",
    image: '/images/thadlaskein.jpg',
    coordinates: { lat: 25.45, lng: 92.22 },
    tags: ['nature', 'lakes', 'culture'],
    budget: 'low',
    temperature: { min: 14, max: 26 },
    bestTime: 'October – May',
    highlights: ['Sacred lake', 'Monoliths', 'Boating', 'Picnic spots'],
    activities: ['Boating', 'Fishing', 'Photography', 'Picnic', 'Cultural tour', 'Monolith viewing'],
    entryFee: 'Free',
    visitDuration: 2,
  },
  {
    name: 'Nartiang Monoliths',
    district: 'West Jaintia Hills',
    description: "Nartiang is home to the largest concentration of monoliths (menhirs and dolmens) in the world, erected between the 15th and 19th centuries by Jaintia kings. The towering stone pillars — some over 8 metres tall — stand in a sacred grove and are a UNESCO heritage nomination.",
    image: '/images/thadlaskein.jpg',
    coordinates: { lat: 25.4944, lng: 92.3208 },
    tags: ['heritage', 'culture'],
    budget: 'low',
    temperature: { min: 14, max: 26 },
    bestTime: 'October – May',
    highlights: ["World's largest monolith concentration", 'Jaintia royal history', '8 m tall standing stones', 'Sacred grove'],
    activities: ['Heritage sightseeing', 'Photography', 'Cultural tour', 'Historical learning', 'Village walk'],
    entryFee: 'Free',
    visitDuration: 2,
  },
  {
    name: 'Umlawan Cave',
    district: 'East Jaintia Hills',
    description: "One of the deepest and longest cave systems in South Asia, Umlawan stretches over 11 km through the Jaintia Hills limestone belt. The cave hosts vast chambers, underground rivers, and rare cave flora — strictly for experienced spelunkers with guides.",
    image: '/images/arwah.jpg',
    coordinates: { lat: 25.312, lng: 92.574 },
    tags: ['caves', 'adventure'],
    budget: 'medium',
    temperature: { min: 14, max: 24 },
    bestTime: 'November – March',
    highlights: ['11 km cave system', 'Underground rivers', 'Rare cave flora', 'Expert expeditions only'],
    activities: ['Expert spelunking', 'Cave diving (advanced)', 'Guided caving', 'Photography', 'Scientific exploration'],
    entryFee: '₹500 (guided)',
    visitDuration: 5,
  },

  // ── West Khasi Hills ──────────────────────────────────────────────────────
  {
    name: 'Pelga Falls',
    district: 'West Khasi Hills',
    description: "A secluded multi-tiered waterfall in the West Khasi Hills, Pelga Falls rewards adventurous trekkers with its dramatic plunge into a rocky gorge. The surrounding landscape of rolling hills and pine trees is stunning.",
    image: '/images/pelga.jpg',
    coordinates: { lat: 25.42, lng: 91.52 },
    tags: ['waterfalls', 'nature', 'adventure'],
    budget: 'low',
    temperature: { min: 12, max: 26 },
    bestTime: 'July – September',
    highlights: ['Multi-tiered falls', 'Gorge views', 'Adventure trek', 'Pine forest'],
    activities: ['Trekking', 'Swimming', 'Photography', 'Nature walk'],
    entryFee: 'Free',
    visitDuration: 3,
  },

  // ── Garo Hills ────────────────────────────────────────────────────────────
  {
    name: 'Balpakram National Park',
    district: 'South Garo Hills',
    description: "Known as the 'Land of Perpetual Winds' and considered sacred by the Garo tribe, Balpakram is home to rare wildlife including red pandas and elephants. Its dramatic gorges and bison reserves are spectacular.",
    image: '/images/balpakram.jpg',
    coordinates: { lat: 25.1667, lng: 90.7833 },
    tags: ['nature', 'adventure', 'wildlife'],
    budget: 'medium',
    temperature: { min: 18, max: 32 },
    bestTime: 'November – March',
    highlights: ['Red pandas', 'Dramatic gorges', 'Garo sacred site', 'Wildlife safari'],
    activities: ['Wildlife safari', 'Bird watching', 'Trekking', 'Photography', 'Jeep safari', 'Camping'],
    entryFee: '₹200',
    visitDuration: 5,
  },
  {
    name: 'Nokrek National Park',
    district: 'West Garo Hills',
    description: "A UNESCO biosphere reserve and the only habitat of the rare red panda in Meghalaya, Nokrek National Park protects pristine forest ecosystems. The trek to the peak offers magnificent views of the Garo Hills.",
    image: '/images/nokrek.jpg',
    coordinates: { lat: 25.5, lng: 90.4167 },
    tags: ['nature', 'adventure', 'wildlife'],
    budget: 'medium',
    temperature: { min: 15, max: 30 },
    bestTime: 'November – March',
    highlights: ['UNESCO biosphere', 'Red pandas', 'Nokrek peak trek', 'Pristine forests'],
    activities: ['Wildlife spotting', 'Trekking', 'Bird watching', 'Photography', 'Peak summit', 'Nature walk'],
    entryFee: '₹150',
    visitDuration: 4,
  },
  {
    name: 'Siju Cave',
    district: 'South Garo Hills',
    description: "One of the largest river caves in the Indian subcontinent, Siju Cave runs for several kilometres along the Simsang River. Famous for its fossil formations, massive stalactites, and horseshoe bats, it offers a true caving expedition.",
    image: '/images/siju.jpg',
    coordinates: { lat: 25.3167, lng: 90.7167 },
    tags: ['caves', 'adventure', 'wildlife'],
    budget: 'medium',
    temperature: { min: 18, max: 30 },
    bestTime: 'November – March',
    highlights: ['River cave', 'Horseshoe bats', 'Massive stalactites', 'Expert-guided tours'],
    activities: ['Cave exploration', 'Bat watching', 'Spelunking', 'Guided caving tour', 'Photography', 'River walk'],
    entryFee: '₹100',
    visitDuration: 3,
  },
  {
    name: 'Tura Peak',
    district: 'West Garo Hills',
    description: "Rising 872 m above Tura town, the trek to Tura Peak passes through dense jungle and offers sweeping views of the Garo Hills and Brahmaputra plains. It's a favourite with birders, trekkers, and sunrise chasers.",
    image: '/images/tura.jpg',
    coordinates: { lat: 25.5, lng: 90.2333 },
    tags: ['nature', 'adventure'],
    budget: 'low',
    temperature: { min: 15, max: 30 },
    bestTime: 'October – April',
    highlights: ['Jungle trek', 'Panoramic views', 'Bird watching', 'Sunrise spot'],
    activities: ['Trekking', 'Bird watching', 'Sunrise viewing', 'Photography', 'Peak summit'],
    entryFee: 'Free',
    visitDuration: 4,
  },
  {
    name: 'Williamnagar',
    district: 'East Garo Hills',
    description: "The headquarters of East Garo Hills, Williamnagar is a charming town surrounded by dense sal forests, rivers, and Garo tribal villages. The nearby Sibbari Forest and Rongjeng River make it a peaceful nature base for eastern Garo Hills exploration.",
    image: '/images/balpakram.jpg',
    coordinates: { lat: 25.4980, lng: 90.6125 },
    tags: ['nature', 'culture', 'wildlife'],
    budget: 'low',
    temperature: { min: 16, max: 32 },
    bestTime: 'November – March',
    highlights: ['Sal forest treks', 'Garo tribal culture', 'Rongjeng River', 'Sibbari Forest'],
    activities: ['Forest trekking', 'Cultural tour', 'River walk', 'Bird watching', 'Village visit', 'Fishing'],
    entryFee: 'Free',
    visitDuration: 2,
  },
  {
    name: 'Baghmara',
    district: 'South Garo Hills',
    description: "The gateway to Balpakram National Park and Siju Cave, Baghmara town sits on the banks of the Simsang River. The lush surroundings, Garo tribal heritage, and access to wildlife-rich forests make it the essential Garo Hills base camp.",
    image: '/images/siju.jpg',
    coordinates: { lat: 25.1956, lng: 90.6419 },
    tags: ['nature', 'wildlife', 'culture'],
    budget: 'low',
    temperature: { min: 18, max: 34 },
    bestTime: 'November – March',
    highlights: ['Gateway to Balpakram', 'Simsang River', 'Garo tribal culture', 'Wildlife base camp'],
    activities: ['Wildlife safari base', 'River boating', 'Cultural tour', 'Photography', 'Fishing', 'Village walk'],
    entryFee: 'Free',
    visitDuration: 2,
  },

];

export const SEED_ADMIN = {
  name: 'Admin',
  email: 'admin@meghalaya.com',
  password: 'Admin@123',
  role: 'admin' as const,
  preferences: {
    budget: 'high' as const,
    interests: ['nature', 'culture'],
    travelDuration: 7,
  },
};
